#!/bin/sh
# Format workspace qcow2 if needed, write WebDAV secrets from QEMU fw_cfg,
# configure egress proxy and secret env vars, install MITM CA cert, and mount
# /workspace.
set -e

mkdir -p /workspace /host-workspace

# Format workspace disk safely ONLY if not already formatted (prevents data
# loss on reboot). blkid exits non-zero when no filesystem is detected.
if [ -b /dev/vdb ]; then
  if ! blkid /dev/vdb >/dev/null 2>&1; then
    echo "Formatting /dev/vdb as ext4..."
    mkfs.ext4 -F -q /dev/vdb
  fi
fi

# Explicitly mount /workspace if not already mounted. On a subsequent boot
# systemd may mount it early via the fstab-generated workspace.mount, but on
# the very first boot (disk unformatted at fstab parse time) we must handle it.
if [ -b /dev/vdb ] && ! mountpoint -q /workspace; then
  echo "Mounting /dev/vdb on /workspace..."
  mount -o noatime /dev/vdb /workspace
fi

# ---- Read kernel cmdline parameters ----
# These are set by the host in qemu.ts -append.
proxy_port=$(sed -n 's/.*valencebox\.proxy_port=\([0-9]*\).*/\1/p' /proc/cmdline)
proxy_token=$(sed -n 's/.*valencebox\.proxy_token=\([^ ]*\).*/\1/p' /proc/cmdline)
secrets_raw=$(sed -n 's/.*valencebox\.secrets=\([^ ]*\).*/\1/p' /proc/cmdline)

# ---- Read QEMU fw_cfg config ----
# The host writes these files before boot; they are not visible on the command line.
modprobe qemu_fw_cfg 2>/dev/null || true

FW_CFG_BASE="/sys/firmware/qemu_fw_cfg/by_name"

share_config_path="${FW_CFG_BASE}/opt/org.valencebox.config/raw"
if [ -f "$share_config_path" ]; then
  SHARE_RAW=$(cat "$share_config_path")
  port=$(echo "$SHARE_RAW" | sed -n 's/.*"port":\([0-9]*\).*/\1/p')
  token=$(echo "$SHARE_RAW" | sed -n 's/.*"token":"\([^"]*\)".*/\1/p')
fi

# ---- WebDAV share ----
if [ -n "$port" ] && [ -n "$token" ]; then
  mkdir -p /etc/davfs2
  echo "http://10.0.2.2:${port}/ valence ${token}" > /etc/davfs2/secrets
  chmod 0600 /etc/davfs2/secrets
  chown 0:0 /etc/davfs2/secrets 2>/dev/null || true
  chown 0:0 /etc/davfs2 2>/dev/null || true

  mkdir -p /var/cache/davfs2
  chmod 0700 /var/cache/davfs2
fi

# ---- MITM CA certificate (if provided via fw_cfg) ----
mitm_ca_path="${FW_CFG_BASE}/opt/org.valencebox.mitm-ca/raw"
if [ -f "$mitm_ca_path" ]; then
  CA_CERT=$(cat "$mitm_ca_path")
  if [ -n "$CA_CERT" ]; then
    echo "$CA_CERT" > /usr/local/share/ca-certificates/valencebox-mitm.crt
    chmod 0644 /usr/local/share/ca-certificates/valencebox-mitm.crt
    update-ca-certificates 2>/dev/null || true
    echo "Installed MITM CA certificate"
  fi
fi

# ---- Egress proxy environment ----
if [ -n "$proxy_port" ] && [ -n "$proxy_token" ]; then
  cat > /etc/profile.d/valencebox-proxy.sh <<'PROXYEOF'
# ValenceBox egress proxy configuration.
# Set by mount-share.sh from kernel cmdline parameters.
HTTP_PROXY="http://valencebox:PROXY_TOKEN@10.0.2.2:PROXY_PORT/"
HTTPS_PROXY="http://valencebox:PROXY_TOKEN@10.0.2.2:PROXY_PORT/"
NO_PROXY="127.0.0.1,localhost,10.0.2.2,::1"
NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/valencebox-mitm.crt
export HTTP_PROXY HTTPS_PROXY http_proxy https_proxy NO_PROXY no_proxy NODE_EXTRA_CA_CERTS
PROXYEOF

  # Substitute actual values sed -i is portable across Linux distros.
  sed -i "s/PROXY_TOKEN/${proxy_token}/g; s/PROXY_PORT/${proxy_port}/g" /etc/profile.d/valencebox-proxy.sh
  chmod 0644 /etc/profile.d/valencebox-proxy.sh

  # Also export for the current shell (mount-share runs as root from systemd).
  export HTTP_PROXY="http://valencebox:${proxy_token}@10.0.2.2:${proxy_port}/"
  export HTTPS_PROXY="http://valencebox:${proxy_token}@10.0.2.2:${proxy_port}/"
  export NO_PROXY="127.0.0.1,localhost,10.0.2.2,::1"
  export NODE_EXTRA_CA_CERTS="/usr/local/share/ca-certificates/valencebox-mitm.crt"
  export http_proxy="$HTTP_PROXY"
  export https_proxy="$HTTPS_PROXY"
  export no_proxy="$NO_PROXY"
fi

# ---- Secret placeholders ----
if [ -n "$secrets_raw" ]; then
  {
    echo "# ValenceBox secret placeholders (injected by host egress proxy)"
    echo "# Real values are never exposed to the guest."
    echo "# This file is generated by mount-share.sh from kernel cmdline."

    # Format from host: "ENV1=placeholder1,ENV2=placeholder2"
    IFS=","
    for pair in $secrets_raw; do
      env_name="${pair%%=*}"
      env_val="${pair#*=}"
      echo "export ${env_name}=\"${env_val}\""
      eval "export ${env_name}=\"${env_val}\""
    done
  } > /etc/profile.d/valencebox-secrets.sh
  chmod 0644 /etc/profile.d/valencebox-secrets.sh
fi
